### ISSUE TITLE
Can I run the IV regression using the given data?

### ISSUE THREAD

**Issue by chengjun** [rajkumarkarthik/weak_ties_data_and_code#1]
Hi @rajkumarkarthik 

Congratulations on this great piece of study. I double-checked the given R script and find that only the R script for OLS regression is given. Can I run the IV regression using the given data? Thanks a lot.

**Comment by rajkumarkarthik** [comment]
Hi Cheng-Jun,

Yes, as noted in the SM, the released data includes replication code only for the OLS regressions, but I believe all summary statistics (means and covariances) include the instruments. 

Best,
Karthik
